version: "4"
services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:postgres
      POSTGRES_DB: mycloud
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
      POSTGRES_SCHEMA: public
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "mycloud"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  mailhog:
    image: mailhog/mailhog
    container_name: mycloud_mailhog
    restart: always 
    ports:
      - "1025:1025"  # Porta SMTP
      - "8025:8025"  # Interface Web para visualizar os e-mails
  redis:
    image: redis:latest
    container_name: mycloud_redis
    restart: always
    ports:
      - "6379:6379"